# Details
mod_author=Asphocarp
mod_name=Sophisticated Ping
mod_id=sophisticated_ping
forge_mod_id=sophisticated_ping
archive_name=sophisticated_ping
contributors=
license=MIT AND CC0-1.0
description=Make MC Apex Again!
link_home=https://github.com/junyudev/sophisticated-ping
link_src=https://github.com/junyudev/sophisticated-ping
link_issues=https://github.com/junyudev/sophisticated-ping/issues

# Common
mod_version=1.2.5
maven_group=app.jyu

# Minecraft
minecraft_version=1.19.2
java_version=17

# Fabric
fabric_version=0.76.0+1.19.2
fabric_loader_version=0.14.21
fabric_loader_min_version=0.14.9
fabric_compatible_range=>=1.19 <=1.19.2
loom_version=1.10-SNAPSHOT
modmenu_version=4.2.0-beta.2
cloth_version=8.2.88
distanthorizons_api_version=5.1.0

# Forge
forge_version=43.3.0
forge_loader_version=43
forge_compatible_range=[1.19,1.19.2]

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
