# Details
mod_author=Asphocarp
mod_name=Sophisticated Ping
mod_id=sophisticated_ping
forge_mod_id=sophisticated_ping
archive_name=Sophisticated_Ping
contributors=
license=CC0-1.0
description=Make MC Apex Again!
link_home=https://github.com/Asphocarp/sophisticated-ping
link_src=https://github.com/Asphocarp/sophisticated-ping
link_issues=https://github.com/Asphocarp/sophisticated-ping/issues

# Common
mod_version=1.2.1
maven_group=app.jyu

# Minecraft
minecraft_version=1.19.3
java_version=17

# Fabric
fabric_version=0.76.1+1.19.3
fabric_loader_version=0.14.21
fabric_compatible_range=1.19.3
loom_version=1.9-SNAPSHOT
modmenu_version=5.0.2
cloth_version=9.0.94

# Forge
forge_version=44.1.0
forge_loader_version=44
forge_compatible_range=[1.19.3]

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
