# Details
mod_author=Asphocarp
mod_name=Sophisticated Ping
mod_id=sophisticated_ping
forge_mod_id=sophisticated_ping
archive_name=sophisticated_ping
contributors=
license=MIT AND CC0-1.0
description=Make MC Apex Again!
link_home=https://github.com/junyudev/sophisticated-ping
link_src=https://github.com/junyudev/sophisticated-ping
link_issues=https://github.com/junyudev/sophisticated-ping/issues

# Common
mod_version=1.2.3
maven_group=app.jyu

# Minecraft
minecraft_version=1.20.1
java_version=17

# Fabric
fabric_version=0.92.5+1.20.1
fabric_loader_version=0.16.10
fabric_loader_min_version=0.14.21
fabric_compatible_range=>=1.20 <=1.20.1
loom_version=1.10-SNAPSHOT
modmenu_version=7.2.2
cloth_version=11.1.136
distanthorizons_api_version=5.1.0

# Forge
forge_version=47.2.1
forge_loader_version=47
forge_compatible_range=[1.20,1.20.1]

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
